
import { EVTransaction, PricingRule, Translations } from './types';

export const INITIAL_PRICING_RULES: PricingRule[] = [];

export const TRANSLATIONS: Translations = {
  dashboard: { en: 'Dashboard', es: 'Tablero' },
  transactions: { en: 'Transactions', es: 'Transacciones' },
  aiInsights: { en: 'AI Insights', es: 'Información IA' },
  pricingRules: { en: 'Pricing Settings', es: 'Ajustes de Precios' },
  reports: { en: 'Account Reports', es: 'Reportes por Cuenta' },
  expenses: { en: 'Expenses', es: 'Gastos' },
  importCsv: { en: 'Import CSV', es: 'Importar CSV' },
  networkOverview: { en: 'Network Overview', es: 'Vista General de Red' },
  performanceMetrics: { en: 'Real-time performance metrics.', es: 'Métricas de rendimiento en tiempo real.' },
  totalEnergy: { en: 'Total Energy', es: 'Energía Total' },
  totalRevenue: { en: 'Total Revenue', es: 'Ingresos Totales' },
  totalExpenses: { en: 'Total Expenses', es: 'Gastos Totales' },
  netProfit: { en: 'Net Profit', es: 'Utilidad Neta' },
  avgSession: { en: 'Avg. Session', es: 'Sesión Promedio' },
  activeUsers: { en: 'Active Accounts', es: 'Cuentas Activas' },
  energyTrend: { en: 'Energy Consumption Trend', es: 'Tendencia de Consumo de Energía' },
  revenueByStation: { en: 'Revenue by Station', es: 'Ingresos por Estación' },
  revenueByAccount: { en: 'Revenue by Account', es: 'Ingresos por Cuenta' },
  topStations: { en: 'Top Stations', es: 'Estaciones Principales' },
  advancedFilters: { en: 'Advanced Filters', es: 'Filtros Avanzados' },
  resetFilters: { en: 'Reset Filters', es: 'Restablecer Filtros' },
  dateStart: { en: 'Date Start', es: 'Fecha Inicio' },
  dateEnd: { en: 'Date End', es: 'Fecha Fin' },
  station: { en: 'Station', es: 'Estación' },
  account: { en: 'Account', es: 'Cuenta' },
  export: { en: 'Export CSV', es: 'Exportar CSV' },
  clear: { en: 'Clear', es: 'Limpiar' },
  txId: { en: 'TxID', es: 'ID Transacción' },
  connector: { en: 'Connector', es: 'Conector' },
  usage: { en: 'Usage (kWh)', es: 'Uso (kWh)' },
  cost: { en: 'Cost ($COP)', es: 'Costo ($COP)' },
  startTime: { en: 'Start Time', es: 'Hora Inicio' },
  endTime: { en: 'End Time', es: 'Hora Fin' },
  duration: { en: 'Duration', es: 'Duración' },
  ratePerKWh: { en: 'Rate per kWh', es: 'Tarifa por kWh' },
  addRule: { en: 'Add Pricing Rule', es: 'Agregar Regla de Precio' },
  delete: { en: 'Delete', es: 'Eliminar' },
  noRules: { en: 'No custom rules defined.', es: 'No hay reglas personalizadas definidas.' },
  accountOverview: { en: 'Account Billing Overview', es: 'Resumen de Facturación por Cuenta' },
  totalSessions: { en: 'Sessions', es: 'Sesiones' },
  rate: { en: 'Rate', es: 'Tarifa' },
  status: { en: 'Status', es: 'Estado' },
  paymentType: { en: 'Payment Type', es: 'Tipo de Pago' },
  paymentDate: { en: 'Payment Date', es: 'Fecha de Pago' },
  totalPaid: { en: 'Total Paid', es: 'Total Pagado' },
  totalUnpaid: { en: 'Total Unpaid', es: 'Total Pendiente' },
  edit: { en: 'Edit', es: 'Editar' },
  addExpense: { en: 'Add Expense', es: 'Agregar Gasto' },
  expenseDescription: { en: 'Description', es: 'Descripción' },
  expenseAmount: { en: 'Amount ($COP)', es: 'Monto ($COP)' },
  expenseDate: { en: 'Date', es: 'Fecha' },
};

export const MOCK_DATA: EVTransaction[] = [];
