
import { EVTransaction, PricingRule, Translations } from './types';

export const INITIAL_PRICING_RULES: PricingRule[] = [];

export const TRANSLATIONS: Translations = {
  dashboard: { en: 'Dashboard', es: 'Tablero' },
  transactions: { en: 'Transactions', es: 'Transacciones' },
  aiInsights: { en: 'AI Insights', es: 'Información IA' },
  pricingRules: { en: 'Pricing Settings', es: 'Ajustes de Precios' },
  reports: { en: 'Account Reports', es: 'Reportes por Cuenta' },
  expenses: { en: 'Expenses', es: 'Gastos' },
  importCsv: { en: 'Import CSV', es: 'Importar CSV' },
  networkOverview: { en: 'Network Overview', es: 'Vista General de Red' },
  performanceMetrics: { en: 'Real-time performance metrics.', es: 'Métricas de rendimiento en tiempo real.' },
  totalEnergy: { en: 'Total Energy', es: 'Energía Total' },
  totalRevenue: { en: 'Total Revenue', es: 'Ingresos Totales' },
  totalExpenses: { en: 'Total Expenses', es: 'Gastos Totales' },
  netProfit: { en: 'Net Profit', es: 'Utilidad Neta' },
  avgSession: { en: 'Avg. Session', es: 'Sesión Promedio' },
  activeUsers: { en: 'Active Accounts', es: 'Cuentas Activas' },
  energyTrend: { en: 'Energy Consumption Trend', es: 'Tendencia de Consumo de Energía' },
  revenueByStation: { en: 'Revenue by Station', es: 'Ingresos por Estación' },
  revenueByAccount: { en: 'Revenue by Account', es: 'Ingresos por Cuenta' },
  topStations: { en: 'Top Stations', es: 'Estaciones Principales' },
  advancedFilters: { en: 'Advanced Filters', es: 'Filtros Avanzados' },
  resetFilters: { en: 'Reset Filters', es: 'Restablecer Filtros' },
  dateStart: { en: 'Date Start', es: 'Fecha Inicio' },
  dateEnd: { en: 'Date End', es: 'Fecha Fin' },
  station: { en: 'Station', es: 'Estación' },
  account: { en: 'Account', es: 'Cuenta' },
  export: { en: 'Export CSV', es: 'Exportar CSV' },
  clear: { en: 'Clear', es: 'Limpiar' },
  txId: { en: 'TxID', es: 'ID Transacción' },
  connector: { en: 'Connector', es: 'Conector' },
  usage: { en: 'Usage (kWh)', es: 'Uso (kWh)' },
  cost: { en: 'Cost ($COP)', es: 'Costo ($COP)' },
  startTime: { en: 'Start Time', es: 'Hora Inicio' },
  endTime: { en: 'End Time', es: 'Hora Fin' },
  duration: { en: 'Duration', es: 'Duración' },
  ratePerKWh: { en: 'Rate per kWh', es: 'Tarifa por kWh' },
  addRule: { en: 'Add Pricing Rule', es: 'Agregar Regla de Precio' },
  delete: { en: 'Delete', es: 'Eliminar' },
  noRules: { en: 'No custom rules defined.', es: 'No hay reglas personalizadas definidas.' },
  accountOverview: { en: 'Account Billing Overview', es: 'Resumen de Facturación por Cuenta' },
  totalSessions: { en: 'Sessions', es: 'Sesiones' },
  rate: { en: 'Rate', es: 'Tarifa' },
  status: { en: 'Status', es: 'Estado' },
  paymentType: { en: 'Payment Type', es: 'Tipo de Pago' },
  paymentDate: { en: 'Payment Date', es: 'Fecha de Pago' },
  totalPaid: { en: 'Total Paid', es: 'Total Pagado' },
  totalUnpaid: { en: 'Total Unpaid', es: 'Total Pendiente' },
  edit: { en: 'Edit', es: 'Editar' },
  addExpense: { en: 'Add Expense', es: 'Agregar Gasto' },
  expenseDescription: { en: 'Description', es: 'Descripción' },
  expenseAmount: { en: 'Amount ($COP)', es: 'Monto ($COP)' },
  expenseDate: { en: 'Date', es: 'Fecha' },
  financialTrends: { en: 'Financial Trends', es: 'Tendencias Financieras' },
  revenueVsExpenses: { en: 'Revenue vs Expenses', es: 'Ingresos vs Gastos' },
  paymentDistribution: { en: 'Payment Distribution', es: 'Distribución de Pagos' },
  editTransaction: { en: 'Edit Transaction', es: 'Editar Transacción' },
  saveChanges: { en: 'Save Changes', es: 'Guardar Cambios' },
  cancel: { en: 'Cancel', es: 'Cancelar' },
  importTransactions: { en: 'Import Transactions', es: 'Importar Transacciones' },
  dropCsv: { en: 'Drop your CSV export here', es: 'Arrastra tu exportación CSV aquí' },
  browseFiles: { en: 'Browse Files', es: 'Buscar Archivos' },
  validatingEntries: { en: 'Validating entries...', es: 'Validando entradas...' },
  newTransactions: { en: 'New Transactions', es: 'Nuevas Transacciones' },
  duplicatesSkipped: { en: 'Duplicates Skipped', es: 'Duplicados Omitidos' },
  finalizeImport: { en: 'Finalize Import', es: 'Finalizar Importación' },
  analyzing: { en: 'Analyzing...', es: 'Analizando...' },
  refreshAi: { en: 'Refresh AI', es: 'Refrescar IA' },
  accountGroupings: { en: 'Account Groupings', es: 'Agrupaciones de Cuentas' },
  createGroup: { en: 'Create Group', es: 'Crear Grupo' },
  targetType: { en: 'Target Type', es: 'Tipo de Objetivo' },
  targetEntity: { en: 'Target Entity', es: 'Entidad Objetivo' },
  howPricingCalculated: { en: 'How Pricing is Calculated', es: 'Cómo se Calcula el Precio' },
  printUserStatement: { en: 'Print User Statement', es: 'Imprimir Estado de Usuario' },
  exportPdf: { en: 'Export PDF', es: 'Exportar PDF' },
  allYears: { en: 'All Years', es: 'Todos los Años' },
  allStations: { en: 'All Stations', es: 'Todas las Estaciones' },
  allAccounts: { en: 'All Accounts', es: 'Todas las Cuentas' },
  year: { en: 'Year', es: 'Año' },
  aiAnalysisSubtitle: { en: 'Smart Charge infrastructure analysis via Gemini.', es: 'Análisis de infraestructura Smart Charge vía Gemini.' },
  pricingRulesSubtitle: { en: 'Manage Account Groups and fine-tune pricing hierarchies.', es: 'Gestione grupos de cuentas y refine las jerarquías de precios.' },
  expensesSubtitle: { en: 'Track operational costs and infrastructure maintenance.', es: 'Rastree costos operativos y mantenimiento de infraestructura.' },
  searchAccountPlaceholder: { en: 'Search Account or ID...', es: 'Buscar Cuenta o ID...' },
  selected: { en: 'Selected', es: 'Seleccionados' },
  invoice: { en: 'Invoice', es: 'Factura' },
  printInvoice: { en: 'Print Invoice', es: 'Imprimir Factura' },
  billTo: { en: 'Bill To', es: 'Facturar a' },
  description: { en: 'Description', es: 'Descripción' },
  total: { en: 'Total', es: 'Total' },
  apiIntegration: { en: 'API Integration', es: 'Integración API' },
  apiUrl: { en: '3rd Party API URL', es: 'URL de API de Terceros' },
  apiKey: { en: 'API Key', es: 'Clave de API' },
  enableIntegration: { en: 'Enable Integration', es: 'Activar Integración' },
  saveConfig: { en: 'Save Configuration', es: 'Guardar Configuración' },
  ocppIntegration: { en: 'OCPP 1.6 Integration', es: 'Integración OCPP 1.6' },
  ocppStatus: { en: 'OCPP Server Status', es: 'Estado del Servidor OCPP' },
  liveMonitor: { en: 'Live Monitor', es: 'Monitor en Vivo' },
  stationId: { en: 'Station ID', es: 'ID de Estación' },
  userManagement: { en: 'Users & RFID', es: 'Usuarios y RFID' },
  userList: { en: 'User Directory', es: 'Directorio de Usuarios' },
  addUser: { en: 'Add Profile', es: 'Agregar Perfil' },
  userName: { en: 'Full Name', es: 'Nombre Completo' },
  userEmail: { en: 'Email Address', es: 'Correo Electrónico' },
  cedula: { en: 'Cédula', es: 'Cédula' },
  nit: { en: 'NIT', es: 'NIT' },
  companyName: { en: 'Company Name', es: 'Nombre de Empresa' },
  rfidTagUid: { en: 'RFID Tag UID', es: 'UID Tag RFID' },
  placa: { en: 'Placa', es: 'Placa' },
  userManagementSubtitle: { en: 'Manage unified profiles with ID, business data, and RFID tags.', es: 'Gestione perfiles unificados con ID, datos comerciales y tags RFID.' },
  userType: { en: 'User Type', es: 'Tipo de Usuario' },
  personalUser: { en: 'Personal User', es: 'Usuario Personal' },
  businessUser: { en: 'Business User', es: 'Usuario Empresarial' },
  contactNumber: { en: 'Contact Number', es: 'Número de Contacto' },
  obligatoryField: { en: 'Obligatory', es: 'Obligatorio' },
  exportUsers: { en: 'Export Users', es: 'Exportar Usuarios' },
  importUsers: { en: 'Import Users', es: 'Importar Usuarios' },
  chargerManagement: { en: 'EV Chargers', es: 'Cargadores EV' },
  chargerManagementSubtitle: { en: 'Manage charging infrastructure and connector health.', es: 'Gestione la infraestructura de carga y el estado de los conectores.' },
  chargerList: { en: 'Charger Network', es: 'Red de Cargadores' },
  addCharger: { en: 'Add Charger', es: 'Agregar Cargador' },
  editCharger: { en: 'Edit Charger', es: 'Editar Cargador' },
  chargerName: { en: 'Charger Name / ID', es: 'Nombre / ID del Cargador' },
  location: { en: 'Location', es: 'Ubicación' },
  connectors: { en: 'Connectors', es: 'Conectores' },
  addConnector: { en: 'Add Connector', es: 'Agregar Conector' },
  powerKW: { en: 'Power (kW)', es: 'Potencia (kW)' },
  connectorType: { en: 'Type', es: 'Tipo' },
  reboot: { en: 'Reboot Charger', es: 'Reiniciar Cargador' },
  unlock: { en: 'Unlock Connector', es: 'Desbloquear Conector' },
  remoteActions: { en: 'Remote Actions', es: 'Acciones Remotas' },
  liveStatus: { en: 'Live Visibility', es: 'Visibilidad en Vivo' },
};

export const MOCK_DATA: EVTransaction[] = [];
