
import { EVTransaction, PricingRule, Translations } from './types';

export const INITIAL_PRICING_RULES: PricingRule[] = [
  { id: '1', targetId: 'Corporate-A', targetType: 'ACCOUNT', connector: 'Type 2', ratePerKWh: 1100 },
  { id: '2', targetId: 'Corporate-A', targetType: 'ACCOUNT', connector: 'CCS2', ratePerKWh: 1500 },
  { id: '3', targetId: 'Public-User', targetType: 'ACCOUNT', connector: 'Type 2', ratePerKWh: 1350 },
  { id: '4', targetId: 'Public-User', targetType: 'ACCOUNT', connector: 'CCS2', ratePerKWh: 1800 },
  { id: '5', targetId: 'Default', targetType: 'DEFAULT', connector: 'Default', ratePerKWh: 1200 },
];

export const TRANSLATIONS: Translations = {
  dashboard: { en: 'Dashboard', es: 'Tablero' },
  transactions: { en: 'Transactions', es: 'Transacciones' },
  aiInsights: { en: 'AI Insights', es: 'Información IA' },
  pricingRules: { en: 'Pricing Settings', es: 'Ajustes de Precios' },
  reports: { en: 'Account Reports', es: 'Reportes por Cuenta' },
  importCsv: { en: 'Import CSV', es: 'Importar CSV' },
  networkOverview: { en: 'Network Overview', es: 'Vista General de Red' },
  performanceMetrics: { en: 'Real-time performance metrics.', es: 'Métricas de rendimiento en tiempo real.' },
  totalEnergy: { en: 'Total Energy', es: 'Energía Total' },
  totalRevenue: { en: 'Total Revenue', es: 'Ingresos Totales' },
  avgSession: { en: 'Avg. Session', es: 'Sesión Promedio' },
  activeUsers: { en: 'Active Accounts', es: 'Cuentas Activas' },
  energyTrend: { en: 'Energy Consumption Trend', es: 'Tendencia de Consumo de Energía' },
  revenueByStation: { en: 'Revenue by Station', es: 'Ingresos por Estación' },
  revenueByAccount: { en: 'Revenue by Account', es: 'Ingresos por Cuenta' },
  topStations: { en: 'Top Stations', es: 'Estaciones Principales' },
  advancedFilters: { en: 'Advanced Filters', es: 'Filtros Avanzados' },
  resetFilters: { en: 'Reset Filters', es: 'Restablecer Filtros' },
  dateStart: { en: 'Date Start', es: 'Fecha Inicio' },
  dateEnd: { en: 'Date End', es: 'Fecha Fin' },
  station: { en: 'Station', es: 'Estación' },
  account: { en: 'Account', es: 'Cuenta' },
  export: { en: 'Export CSV', es: 'Exportar CSV' },
  clear: { en: 'Clear', es: 'Limpiar' },
  txId: { en: 'TxID', es: 'ID Transacción' },
  connector: { en: 'Connector', es: 'Conector' },
  usage: { en: 'Usage (kWh)', es: 'Uso (kWh)' },
  cost: { en: 'Cost ($COP)', es: 'Costo ($COP)' },
  startTime: { en: 'Start Time', es: 'Hora Inicio' },
  endTime: { en: 'End Time', es: 'Hora Fin' },
  duration: { en: 'Duration', es: 'Duración' },
  ratePerKWh: { en: 'Rate per kWh', es: 'Tarifa por kWh' },
  addRule: { en: 'Add Pricing Rule', es: 'Agregar Regla de Precio' },
  delete: { en: 'Delete', es: 'Eliminar' },
  noRules: { en: 'No custom rules defined.', es: 'No hay reglas personalizadas definidas.' },
  accountOverview: { en: 'Account Billing Overview', es: 'Resumen de Facturación por Cuenta' },
  totalSessions: { en: 'Sessions', es: 'Sesiones' },
  rate: { en: 'Rate', es: 'Tarifa' },
  status: { en: 'Status', es: 'Estado' },
  paymentType: { en: 'Payment Type', es: 'Tipo de Pago' },
  paymentDate: { en: 'Payment Date', es: 'Fecha de Pago' },
  totalPaid: { en: 'Total Paid', es: 'Total Pagado' },
  totalUnpaid: { en: 'Total Unpaid', es: 'Total Pendiente' },
  edit: { en: 'Edit', es: 'Editar' },
};

export const MOCK_DATA: EVTransaction[] = [
  {
    id: 'TX-9901',
    station: 'Downtown Plaza',
    connector: 'CCS2',
    account: 'Corporate-A',
    startTime: '2024-05-01T08:30:00Z',
    endTime: '2024-05-01T09:45:00Z',
    meterKWh: 45.5,
    costCOP: 68250,
    durationMinutes: 75,
    appliedRate: 1500,
    status: 'PAID',
    paymentType: 'NEQUI',
    paymentDate: '2024-05-01T10:00:00Z'
  },
  {
    id: 'TX-9902',
    station: 'Riverside Mall',
    connector: 'Type 2',
    account: 'Public-User',
    startTime: '2024-05-01T10:00:00Z',
    endTime: '2024-05-01T11:20:00Z',
    meterKWh: 12.2,
    costCOP: 16470,
    durationMinutes: 80,
    appliedRate: 1350,
    status: 'UNPAID',
    paymentType: 'N/A'
  }
];
